[build]
  publish = "."

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/kyc-aml"
  to = "/kyc-aml.html"
  status = 200

[[redirects]]
  from = "/service-accessibility"
  to = "/service-accessibility.html"
  status = 200

[[redirects]]
  from = "/refund"
  to = "/refund.html"
  status = 200

[[redirects]]
  from = "/legal"
  to = "/legal.html"
  status = 200

[[redirects]]
  from = "/copyright"
  to = "/copyright.html"
  status = 200
